name: Upload Code to S3 bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Create depedndencies folder
        run: |
          pip install -t dependencies -r requirements.txt

      - name: Zip the dependencies folder as aws_lambda_artifacts.zip
        run: |
          (cd dependencies/; zip ../aws_lambda_artifacts.zip -r .)
      
      - name: Update the zip file by adding app folder
        run: |
          (cd app/; zip ../aws_lambda_artifacts.zip -r .); ls

      - name: Verify AWS CLI
        run: |
          aws --version
          aws configure list
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload to S3
        run: |
          aws s3 cp aws_lambda_artifacts.zip s3://${{ secrets.AWS_S3_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
